<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageId>JST.$(AssemblyName)</PackageId>
		<Title>Utilities for games</Title>
		<Authors>John Strand</Authors>
		<Company />
		<Description>A library containing a bunch of methods and types that might be helpful for game development</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/johnstrand/gameutils</RepositoryUrl>
		<PackageProjectUrl>https://github.com/johnstrand/gameutils</PackageProjectUrl>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<Version>1.0.7</Version>
		<WarningLevel>9999</WarningLevel>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<OutputType>Library</OutputType>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Release'">
		<Compile Remove="Program.cs" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\.editorconfig" />
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="SonarAnalyzer.CSharp" Version="10.26.0.140279">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
